// 事件类型 (type)
// 使用常量替代 Mutation 事件类型

export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_IN_THEATERS = 'FETCH_MOVIE_IN_THEATERS';
export const FETCH_MOVIES_COMING_SOON = 'FETCH_MOVIES_COMING_SOON';

export const FETCH_MOVIE_SUBJECT = 'FETCH_MOVIE_SUBJECT';