// 事件类型 (type)
// 使用常量替代 Mutation 事件类型
export const CHANGE_MOVIES_TAB = 'CHANGE_MOVIES_TAB';
export const CHANGE_MOVIES_MENU = 'CHANGE_MOVIES_MENU';

export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_IN_THEATERS = 'FETCH_MOVIE_IN_THEATERS';
export const FETCH_MOVIES_COMING_SOON = 'FETCH_MOVIES_COMING_SOON';

export const FETCH_MOVIE_SUBJECT = 'FETCH_MOVIE_SUBJECT';